
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpnitkphrnswynggtmku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwbml0a3Bocm5zd3luZ2d0bWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjU1NDIsImV4cCI6MjA1Nzg0MTU0Mn0.fTMIqgIMRnoucVNv5yWSGaJVteSoMOeOahpWRmy4WGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
